### PR TITLE
Fix level being overwritten in fixLevel

### PR DESCRIPTION
**Pull request by bloodcarter**

### CODE REVIEW

**Comment by mcollina** [comment]
Can you add a unit test? Also, CI is failing.

**Comment by bloodcarter** [comment]
Look like Github adds trailing spaces when editing inline. I will fix it later on my machine. 
Regarding unit test you mean like here https://github.com/pinojs/pino-multi-stream/blob/master/test/level.test.js ?

**Comment by mcollina** [comment]
Yes. We need a unit test to avoid a regression on this bug.

**Comment by mcollina** [comment]
Closing for no activity.

**Pull request closed without merging**
