### PR TITLE
Added support to pass custom logLevels to `multistream()`

### PR DESCRIPTION
**Pull request by mf-pherlihy**
It looks like the PR that fixes https://github.com/pinojs/pino-multi-stream/issues/23 was never merged:

https://github.com/pinojs/pino-multi-stream/pull/14

This fixes that.

### CODE REVIEW

**Comment by mcollina** [comment]
As I noted last time, this needs a unit test.

**Comment by kehvynko** [comment]
Changes look correct logically and the existing unit test should cover it. Also waiting on a similar feature.

**Comment by mcollina** [comment]
I don’t understand how an existing unit test can cover this.

@kehvynko it seems this is stalled, would you like to send a fresh one?

**Comment by kehvynko** [comment]
The change only affects how we pass in the argument and the rest of the logic is the same. It’s literally just an option to supply your own custom levels.

**Comment by mcollina** [comment]
As all features, it needs a test so we do not regress.

**Pull request closed without merging**
